### PR TITLE
[PLA-3438] the sort by in audit panel

### PR DESCRIPTION
**Pull request by Biomorphix**

### CODE REVIEW

**Comment by enigma91** [comment]
When violations with two different severity level are grouped, color of the first will be used for both of them. Each violation should use it is own color

**Comment by mityakg** [comment]
Will need @george-moberly to check this one

**Comment by george-moberly** [comment]
I'm going to go ahead and merge this so I can test it.

**Comment by george-moberly** [comment]
Ah - no we need each card to retain its proper color for all sorts so I will not merge this now.

**Comment by mityakg** [comment]
Decline this one, changes implemented in pla-3088-fixes-redesign

**Pull request closed without merging**
